// UK lang variables

tinyMCE.addToLang('advlink',{
general_tab : 'Genel',
popup_tab : 'Popup',
events_tab : 'Olaylar',
advanced_tab : 'Geli&#351;mi&#351;',
general_props : 'Genel &ouml;zellikler',
popup_props : 'Popup &ouml;zellikleri',
event_props : 'Olaylar',
advanced_props : 'Geli&#351;mi&#351; &ouml;zellikler',
popup_opts : 'Se&ccedil;enekler',
anchor_names : '&Ccedil;apalar ',
target_same : 'Bu pencerede a&ccedil; / frame',
target_parent : 'Yeni pencerede a&ccedil; / frame',
target_top : ' &Uuml;st Pencerede A&ccedil;',
target_blank : 'Yeni Pencerede A&ccedil;',
popup : 'Javascript popup',
popup_url : 'Popup URL',
popup_name : 'Pencerede Ad&#305;',
popup_return : 'Ekle',
popup_scrollbars : 'Kayd&#305;rma &ccedil;ubuklar&#305;n&#305; g&ouml;r&uuml;nt&uuml;le',
popup_statusbar : 'Durum &ccedil;ubu&#287;unu g&ouml;r&uuml;nt&uuml;le',
popup_toolbar : 'Ara&ccedil; &ccedil;ubuklar&#305;n&#305; g&ouml;r&uuml;nt&uuml;le',
popup_menubar : 'Men&uuml; &ccedil;ubu&#287;unu g&ouml;r&uuml;nt&uuml;le',
popup_location : 'Adres &Ccedil;ubu&#287;unu G&ouml;ster',
popup_resizable : 'Pencere Boyutland&#305;r&#305;labilir Yap',
popup_dependent : 'Dependent (Mozilla/Firefox only)',
popup_size : 'Boyut',
popup_position : 'Pozisyon (X/Y)',
id : 'Id',
style: 'Stil',
classes : 'S&#305;n&#305;flar',
target_name : 'Hedef Ad&#305;',
langdir : 'Dil Y&ouml;netimi',
target_langcode : 'Hedef Y&ouml;netimi',
langcode : 'Dil Kodu',
encoding : 'Hedef Karakter Kodlamas&#305;',
mime : 'Hedef MIME Tipi',
rel : 'Sayfadan Hedefe Ba&#287;lant&#305;',
rev : 'Hedeften Sayfaya Ba&#287;lant&#305;',
tabindex : 'Tabindex',
accesskey : 'Accesskey',
ltr : 'Soldan Sa&#287;a',
rtl : 'Sa&#287;dan Sola'
});