// UK lang variables

tinyMCE.addToLang('table',{
general_tab : 'Genel',
advanced_tab : 'Geli&#351;mi&#351;',
general_props : 'Genel &Ouml;zellikler',
advanced_props : 'Geli&#351;mi&#351; &Ouml;zellikler',
desc : 'Yeni Tablo Ekle',
row_before_desc : '&Uuml;ste Sat&#305;r Ekle',
row_after_desc : 'Alta Sat&#305;r Ekle',
delete_row_desc : 'Sat&#305;r Sil',
col_before_desc : 'Sola S&uuml;tun Ekle',
col_after_desc : 'Sa&#287;a S&uuml;tun Ekle',
delete_col_desc : 'S&uuml;tun Sil',
rowtype : 'Tablonun Sat&#305;rlar&#305;',
title : 'Tablo Ekle/Düzenle',
width : 'Geni&#351;lik',
height : 'Y&uuml;kseklik',
cols : 'S&uuml;tunlar',
rows : 'Sat&#305;rlar',
cellspacing : 'Cellspacing',
cellpadding : 'Cellpadding',
border : 'Border',
align : 'Hizalama',
align_default : 'Default',
align_left : 'Sol',
align_right : 'Sa&#287;',
align_middle : 'Orta',
row_title : 'Tablo Sat&#305;r &Ouml;zellikleri',
cell_title : 'Tablo H&uuml;cre &Ouml;zellikleri',
cell_type : 'H&uuml;cre tipi',
row_desc : 'Tablo Sat&#305;r &Ouml;zellikleri',
cell_desc : 'Tablo H&uuml;cre &Ouml;zellikleri',
valign : 'Dikey Hizalama',
align_top : '&Uuml;st',
align_bottom : 'Alt',
props_desc : 'Tablo &Ouml;zellikleri',
bordercolor : 'Border Rengi',
bgcolor : 'Arkaplan Rengi',
merge_cells_title : 'H&uuml;creleri Birle&#351;tir',
split_cells_desc : 'H&uuml;creleri B&ouml;l',
merge_cells_desc : 'H&uuml;creleri Birle&#351;tir',
cut_row_desc : 'Sat&#305;r&#305; Kes',
copy_row_desc : 'Sat&#305;r&#305; Kopyala',
paste_row_before_desc : 'Sat&#305;r&#305; &Uuml;ste Yap&#305;&#351;t&#305;r',
paste_row_after_desc : 'Sat&#305;r&#305; Alta Yap&#305;&#351;t&#305;r',
id : 'Id',
style: 'Stil',
langdir : 'Dil',
langcode : 'Dil Kodu',
mime : 'Hedef MIME tipi',
ltr : 'Soldan Sa&#287;a',
rtl : 'Sa&#287;dan Sola',
bgimage : 'Arkaplan Resmi',
summary : '&Ouml;zet',
td : "Data",
th : "Ba&#351;l&#305;k",
cell_cell : 'H&uuml;creyi G&uuml;ncelle',
cell_row : 'H&uuml;creleri G&uuml;ncelle',
cell_all : 'H&uuml;creleri G&uuml;ncelle',
row_row : 'Sat&#305;r&#305; G&uuml;ncelle',
row_odd : 'Tablodaki Tek Sat&#305;rlar&#305; G&uuml;ncelle',
row_even : 'Tablodaki &Ccedil;ift Sat&#305;rlar&#305; G&uuml;ncelle',
row_all : 'Tablodaki T&uuml;m Sat&#305;rlar&#305; G&uuml;ncelle',
thead : 'Table Üst',
tbody : 'Table G&ouml;vde',
tfoot : 'Tablo Alt',
del : 'Tabloyu Sil table',
scope : 'Kapsam',
row : 'Sat&#305;r',
col : 'S&uuml;tun',
rowgroup : 'Sat&#305;r Grup',
colgroup : 'S&uuml;tun Grup',
col_limit : 'Maksimum Sat&#305;r Say&#305;s&#305; {$cols} A&#351;t&#305;n&#305;z.',
row_limit : 'Maksimum S&uuml;tun Say&#305;s&#305; {$rows} A&#351;t&#305;n&#305;z.',
cell_limit : 'Maksimum H&uuml;cre Say&#305;s&#305; {$cells} A&#351;t&#305;n&#305;z.',
missing_scope: 'Are you sure you want to continue without specifying a scope for this table header cell. Without it, it may be difficult for some users with disabilities to understand the content or data displayed of the table.',
caption : 'Tablo Ba&#351;l&#305;k'
});
