// UK lang variables

tinyMCE.addToLang('',{
theme_style_select : '-- Stiller --',
theme_code_desc : 'HTML Kayna&#287;&#305; D&uuml;zenle',
theme_code_title : 'HTML Kaynak Edit&ouml;r',
theme_code_wordwrap : 'Word wrap',
theme_sub_desc : 'Alt Simge',
theme_sup_desc : '&Uuml;st Simge',
theme_hr_desc : 'Yatay &Ccedil;izgi Ekle',
theme_removeformat_desc : 'Format&#305; Kald&#305;r',
theme_custom1_desc : '&Ouml;zel Tan&#305;mlama',
insert_image_border : 'Border',
insert_image_dimensions : 'Boyutlar',
insert_image_vspace : 'Dikey Bo&#351;luk',
insert_image_hspace : 'Yatay Bo&#351;luk',
insert_image_align : 'Hizalama',
insert_image_align_default : '-- Not set --',
insert_image_align_baseline : 'Sinir Çizgi',
insert_image_align_top : '&Uuml;s',
insert_image_align_middle : 'Orta',
insert_image_align_bottom : 'Alt',
insert_image_align_texttop : 'TYaz&#305;n&#305;n &Uuml;st&uuml;ne',
insert_image_align_absmiddle : 'Mutlak Orta',
insert_image_align_absbottom : 'Mutlak Alt',
insert_image_align_left : 'Sol',
insert_image_align_right : 'Sa&#287;',
theme_font_size : '-- Font Boyutu --',
theme_fontdefault : '-- Font family --',
theme_block : '-- Format --',
theme_paragraph : 'Paragraf',
theme_div : 'Div',
theme_address : 'Adres',
theme_pre : '&Ouml;n Formatl&#305;',
theme_h1 : 'Heading 1',
theme_h2 : 'Heading 2',
theme_h3 : 'Heading 3',
theme_h4 : 'Heading 4',
theme_h5 : 'Heading 5',
theme_h6 : 'Heading 6',
theme_blockquote : 'Blockquote',
theme_code : 'Kod',
theme_samp : '&Ouml;rnek Kod',
theme_dt : 'Tan&#305;mlama Terimi',
theme_dd : 'Tan&#305;mlama',
theme_colorpicker_title : 'Renk Se&ccedil;',
theme_colorpicker_apply : 'Uygula',
theme_forecolor_desc : 'Text Rengi Se&ccedil;',
theme_backcolor_desc : 'Arkaplan Rengi Se&ccedil;',
theme_charmap_title : '&Ouml;zel Karakter Se&ccedil;',
theme_charmap_desc : '&Ouml;zel Karakter Ekle',
theme_visualaid_desc : 'G&ouml;r&uuml;nmez &Ouml;&#287;eleri G&ouml;r&uuml;nt&uuml;le',
insert_anchor_title : 'Anchor Ekle/Düzenle',
insert_anchor_name : 'Anchor Ad&#305;',
theme_anchor_desc : 'Anchor Ekle/Düzenle',
theme_insert_link_titlefield : 'Ba&#351;l&#305;k',
theme_clipboard_msg : 'Kopyala/Kes/Yap&#305;&#351;t&#305;r &Ouml;zellikleri Mozilla ve Firefoxda mevcut de&#287;il.\nBu konu ile ilgili dahafazla bilgi almak ister misiniz?',
theme_path : 'Yol',
cut_desc : 'Kes',
copy_desc : 'Kopyala',
paste_desc : 'Yap&#305;&#351;t&#305;r',
link_list : 'Link liste',
image_list : 'Resim liste',
browse : 'G&ouml;zat',
image_props_desc : 'Resim &Ouml;zellikleri',
newdocument_desc : 'Yeni D&ouml;k&uuml;man',
class_name : 'S&#305;n&#305;f',
newdocument : 'T&uuml;m i&ccedil;eri&#287;i silmek istedi&#287;inizdem emin misiniz?',
about_title : 'TinyMCE Hakk&#305;nda',
about : 'Hakk&#305;nda',
license : 'Lisans',
plugins : 'Plugins',
plugin : 'Plugin',
author : 'Yazar',
version : 'Versiyon',
loaded_plugins : 'Y&uuml;klenmi&#351; pluginler',
help : 'Yard&#305;m',
not_set : '-- Not set --',
close : 'Kapat',
toolbar_focus : 'Ara&ccedil; Butonlar&#305;na git - Alt+Q, Edit&ouml;re git - Alt-Z, &Ouml;&#287;eye git - Alt-X',
invalid_data : 'Hata: Ge&ccedil;ersiz de&#287;erler girildi, bu de&#287;erler k&#305;rm&#305;z&#305; ile i&#351;aretlendi..',
more_colors : 'Di&#287;er renkler',
color_picker_tab : 'Se&ccedil;ici',
color_picker : 'Renk Se&ccedil;ici',
web_colors_tab : 'Palet',
web_colors : 'Palet Renkleri ',
named_colors_tab : 'Named',
named_colors : 'Named Renkler',
color : 'Renk:',
color_name : 'Ad:',
is_email : 'Eklemis odugunuz URL email adresi olarak görünüyor, bunun için gerekli mailto: ön ekini eklemek istermisiniz?',
is_external : 'Eklemis odugunuz URL bir d&#305;&#351; ba&#287;lant&#305; olarak görünüyor, bunun için gerekli http:// ön ekini eklemek istermisiniz?'
});
