<?
$kategori='Slider';
$title='Slider';		
$uzaklik="../../";
$resim_dizini=$uzaklik."rsmlr/reklam/";
$tablo_ismi='reklamlar';
$bir_sayfadaki_toplam_kayit_sayisi=10000;
$height_of_image=768;
$width_of_image=1920;	
$max_file_size=14000000;
$default_resim="resimyok.gif";	
?>