// UK lang variables

tinyMCE.addToLang('fullpage',{
	title : 'D&ouml;k&uuml;man &Ouml;zellikleri',
	desc : 'D&ouml;k&uuml;man &Ouml;zellikleri',
	meta_tab : 'Genel',
	appearance_tab : 'G&ouml;r&uuml;n&uuml;m',
	advanced_tab : 'Geli&#351;mi&#351;',
	meta_props : 'Meta Bilgi',
	langprops : 'Dil ve Kodlama',
	meta_title : 'Ba&#351;l&#305;k',
	meta_keywords : 'Anahtar Kelimeler',
	meta_description : 'Tan&#305;mlama',
	meta_robots : 'Robotlar',
	doctypes : 'D&ouml;k&uuml;man Tipi',
	langcode : 'Dil Kodu',
	langdir : 'Dil Y&ouml;n&uuml;',
	ltr : 'Soldan Sa&#287;a',
	rtl : 'Sa&#287;dan sola',
	xml_pi : 'XML Tan&#305;mlama',
	encoding : 'Karakter kodlama',
	appearance_bgprops : 'Arkaplan &Ouml;zellikleri',
	appearance_marginprops : 'Sayfa Kenarlar&#305;',
	appearance_linkprops : 'Link Renkleri',
	appearance_textprops : 'Text &Ouml;zellikleri',
	bgcolor : 'Arkaplan Rengi',
	bgimage : 'Arkaplan Resmi',
	left_margin : 'Sol Kenarl&#305;k',
	right_margin : 'Sa&#287; Bo&#351;luk',
	top_margin : '&Uuml;st Bo&#351;luk',
	bottom_margin : 'Alt Bo&#351;luk',
	text_color : 'Yaz&#305; Rengi',
	font_size : 'Yaz&#305; Tipi Boyutu',
	font_face : 'Yaz&#305; Tipi',
	link_color : 'Link Rengi',
	hover_color : '&Uuml;st Rengi',
	visited_color : 'Visited Rengi',
	active_color : 'Aktif Rengi',
	textcolor : 'Renk',
	fontsize : 'Yaz&#305; Tipi Boyutu',
	fontface : 'Yaz&#305; Tipi',
	meta_index_follow : 'linkleri takip et ve indexle',
	meta_index_nofollow : 'indexle ve linkleri takip etme',
	meta_noindex_follow : 'indexleme fakat linkleri takip et',
	meta_noindex_nofollow : 'indexleme fakat linkleri takip etme',
	appearance_style : 'Stylesheet and stil &Ouml;zellikleri',
	stylesheet : 'Stylesheet',
	style : 'Stil',
	author : 'Yazar',
	copyright : 'Copyright',
	add : 'Yeni Eleman Ekle',
	remove : 'Se&ccedil;ili eleman&#305; kald&#305;r',
	moveup : 'Se&ccedil;ili eleman&#305; yukar&#305; ta&#351;&#305;',
	movedown : 'Se&ccedil;ili eleman&#305; a&#351;a&#287;&#305; ta&#351;&#305;',
	head_elements : 'Temel Elemanlar',
	info : 'Bilgi',
	info_text : '',
	add_title : 'Baslik elemani',
	add_meta : 'Meta eleman&#305;',
	add_script : 'Script eleman&#305;',
	add_style : 'Stil eleman&#305;',
	add_link : 'Link eleman&#305;',
	add_base : 'Base eleman&#305;',
	add_comment : 'Comment node',
	title_element : 'Title eleman&#305;',
	script_element : 'Script eleman&#305;',
	style_element : 'Stil eleman&#305;',
	base_element : 'Base eleman&#305;',
	link_element : 'Link eleman&#305;',
	meta_element : 'Meta eleman&#305;',
	comment_element : 'Comment',
	src : 'Kaynak',
	language : 'Dil',
	href : 'Href',
	target : 'Hedef',
	rel : 'Rel',
	type : 'Tip',
	charset : 'Karakter Seti',
	defer : 'Defer',
	media : 'Media',
	properties : '&Ouml;zellikler',
	name : 'Ad',
	value : 'De&#287;er',
	content : '&#304;&ccedil;erik',
	rel : 'Rel',
	rev : 'Rev',
	hreflang : 'Href lang',
	general_props : 'Genel',
	advanced_props : 'Geli&#351;mi&#351;',
	delta_width : 0,
	delta_height : 0
});
