<? 
$slider_modulu=1;
$urun_modulu=0;
$hizmet_modulu=1;
$galeri_modulu=1;
$referans_modulu=0;
$maillist_modulu=0;
$proje_modulu=0;
$ekatalog_modulu=0;
$dosya_modulu=1;
$iletisim_modulu=1;
$formmail_modulu=1;
$haber_modulu=1;
$yenisayfa_etiket_modulu=1;
$video_modulu=0;
$ziyaretci_defteri_modulu=0;
$kullanici_modulu=0;
?>