// UK lang variables

tinyMCE.addToLang('media',{
title : 'Media Ekle/Düzenle',
desc : 'Media Ekle/Düzenle',
general : 'Genel',
advanced : 'Geli&#351;mi&#351;',
file : 'Dosya/URL',
list : 'Liste',
size : 'Boyutlar',
preview : '&Ouml;nizleme',
constrain_proportions : 'S&#305;n&#305;rl&#305; Boyutlar',
type : 'Tipi',
id : 'Id',
name : 'Ad',
class_name : 'S&#305;n&#305;f',
vspace : 'Yatay Bo&#351;luk',
hspace : 'Dikey Bo&#351;luk',
play : 'Otomatik &Ccedil;al&#305;&#351;t&#305;r',
loop : 'Loop',
menu : 'Men&uuml;y&uuml; G&ouml;ster',
quality : 'Kalite',
scale : 'Derece',
align : 'Hizala',
salign : 'SAlign',
wmode : 'WMode',
bgcolor : 'Arkaplan',
base : 'Base',
flashvars : 'Flashvars',
liveconnect : 'SWLiveConnect',
autohref : 'AutoHREF',
cache : 'Cache',
hidden : 'Gizli',
controller : 'Controller',
kioskmode : 'Kiosk mode',
playeveryframe : 'Play every frame',
targetcache : 'Target cache',
correction : 'No correction',
enablejavascript : 'JavaScripti aktive et',
starttime : 'Baslangiç Zamani',
endtime : 'Bitis Zamani',
href : 'Href',
qtsrcchokespeed : 'Choke speed',
target : 'Hedef',
volume : 'Ses',
autostart : 'Otomatik Ba&#351;la',
enabled : 'Aktifle&#351;tir',
fullscreen : 'Tam Ekran',
invokeurls : 'Invoke URLs',
mute : 'Sessiz',
stretchtofit : 'Stretch to fit',
windowlessvideo : 'Windowless video',
balance : 'Balance',
baseurl : 'Base URL',
captioningid : 'Captioning id',
currentmarker : 'Current marker',
currentposition : 'Current position',
defaultframe : 'Default frame',
playcount : 'Play count',
rate : 'Rate',
uimode : 'UI Mode',
flash_options : 'Flash options',
qt_options : 'Quicktime options',
wmp_options : 'Windows media player options',
rmp_options : 'Real media player options',
shockwave_options : 'Shockwave options',
autogotourl : 'Auto goto URL',
center : 'Center',
imagestatus : 'Image status',
maintainaspect : 'Maintain aspect',
nojava : 'No java',
prefetch : 'Prefetch',
shuffle : 'Shuffle',
console : 'Console',
numloop : 'Num loops',
controls : 'Controls',
scriptcallbacks : 'Script callbacks',
swstretchstyle : 'Stretch style',
swstretchhalign : 'Stretch H-Align',
swstretchvalign : 'Stretch V-Align',
sound : 'SEs',
progress : 'Progress',
qtsrc : 'QT Src',
qt_stream_warn : 'Streamed rtsp resources should be added to the QT Src field under the advanced tab.\nYou should also add a non streamed version to the Src field..',
align_top : 'Top',
align_right : 'Right',
align_bottom : 'Bottom',
align_left : 'Left',
align_center : 'Center',
align_top_left : 'Top left',
align_top_right : 'Top right',
align_bottom_left : 'Bottom left',
align_bottom_right : 'Bottom right'
});