// UK lang variables

tinyMCE.addToLang('xhtmlxtras',{
cite_desc : 'Al&#305;nt&#305;',
abbr_desc : 'K&#305;saltma',
acronym_desc : 'K&#305;saad',
del_desc : 'Silme',
ins_desc : 'Ekleme',
attribute_label_title : 'Ba&#351;l&#305;k',
attribute_label_id : 'ID',
attribute_label_class : 'S&#305;n&#305;f',
attribute_label_style : 'Stil',
attribute_label_cite : 'Aktarma',
attribute_label_datetime : 'Tarih/Saat',
attribute_label_langdir : 'Text Y&ouml;nlendirme',
attribute_option_ltr : 'Soldan sa&#287;a',
attribute_option_rtl : 'Sa&#287;dan sola',
attribute_label_langcode : 'Dil',
attribute_label_tabindex : 'TabIndex',
attribute_label_accesskey : 'Eri&#351;im Tu&#351;u',
attribute_label_cite : 'Aktarma',
attribute_events_tab : 'Olaylar',
attribute_attrib_tab : '&Ouml;zellikler',
general_tab : 'Genel',
attrib_tab : '&Ouml;zellikler',
events_tab : 'Olaylar',
fieldset_general_tab : 'Geneal Ayarlar',
fieldset_attrib_tab : 'Eleman &Ouml;zellikleri',
fieldset_events_tab : 'Eleman Olaylar&#305;',
title_ins_element : 'Ekleme',
title_del_element : 'Silme',
title_acronym_element : 'Acronym',
title_abbr_element : 'K&#305;saltma Eleman&#305;',
title_cite_element : 'Citation Element',
remove : '&Ccedil;&#305;kart',
not_set : '--not set--',
insert_date : 'Tarih/Saat Ekle',
option_ltr : 'Soldan Sa&#287;a',
option_rtl : 'Sa&#287;dan Sola',
attribs_desc : '&Ouml;zellik Ekle/D&uuml;zenle',
attribs_title : '&Ouml;zellik Ekle/D&uuml;zenle'
});
