// UK lang variables

tinyMCE.addToLang('style',{
title : 'Edit CSS Style',
styleinfo_desc : 'Edit CSS Style',
apply : 'Uygula',
text_tab : 'Text',
background_tab : 'Arkaplan',
block_tab : 'Blok',
box_tab : 'Box',
border_tab : 'Border',
list_tab : 'List',
positioning_tab : 'Hizalama',
text_props : 'Text',
text_font : 'Font',
text_size : 'Boyut',
text_weight : 'Agirlik',
text_style : 'Stil',
text_variant : 'De&#287;i&#351;ken',
text_lineheight : 'Sat&#305;r Y&uuml;ksekli&#287;i',
text_case : 'Case',
text_color : 'Renk',
text_decoration : 'Dekorasyon',
text_overline : '&Uuml;st &ccedil;izgi',
text_underline : 'Alt &ccedil;izgi',
text_striketrough : 'Orta &ccedil;izgi',
text_blink : 'blink',
text_none : 'none',
background_color : 'Background color',
background_image : 'Arkaplan Rengi',
background_repeat : 'Tekrar',
background_attachment : 'Ek',
background_hpos : 'Yatay pozisyon',
background_vpos : 'Dikey pozisyon',
block_wordspacing : 'Kelime Aral&#305;&#287;&#305;',
block_letterspacing : 'Harf Aral&#305;&#287;&#305;',
block_vertical_alignment : 'Dikey Hizalama',
block_text_align : 'Text hizalama',
block_text_indent : 'Text girinti',
block_whitespace : 'Whitespace',
block_display : 'G&ouml;r&uuml;nt&uuml;',
box_width : 'Geni&#351;lik',
box_height : 'Y&uuml;kseklik',
box_float : 'Float',
box_clear : 'Temizle',
padding : 'Padding',
same : 'Same for all',
top : '&Uuml;st',
right : 'Sa&#287;',
bottom : 'Alt',
left : 'Sol',
margin : 'Margin',
style : 'Stil',
width : 'Geni&#351;lik',
height : 'Y&uuml;kseklik',
color : 'Renk',
list_type : 'Tipi',
bullet_image : 'Bullet image',
position : 'Pozisyon',
positioning_type : 'Tipi',
visibility : 'G&ouml;r&uuml;n&uuml;rl&uuml;k',
zindex : 'Z-index',
overflow : 'Overflow',
placement : 'Placement',
clip : 'Clip'
});
