// UK lang variables

tinyMCE.addToLang('',{
bold_desc : 'Kal&#305;n (Ctrl+B)',
italic_desc : '&#304;talik (Ctrl+I)',
underline_desc : 'Altçizgi (Ctrl+U)',
striketrough_desc : 'Ortaçizgi',
justifyleft_desc : 'Sola Yasla',
justifycenter_desc : 'Ortala',
justifyright_desc : 'Sa&#287;a Yasla',
justifyfull_desc : '&#304;ki Yana Yasla',
bullist_desc : 'Liste',
numlist_desc : 'S&#305;ral&#305; Liste',
outdent_desc : 'Girintiyi Azalt',
indent_desc : 'Girintiyi Arttir',
undo_desc : 'Geri Al (Ctrl+Z)',
redo_desc : 'Yinele (Ctrl+Y)',
link_desc : 'Link Ekle/Düzenle',
unlink_desc : 'Link Kaldir',
image_desc : 'Resim Ekle/Düzenle',
cleanup_desc : 'D&uuml;zensiz Kodlar&#305; Temizle',
focus_alert : 'Bu komutu çalistirmadan önce kontrol text editörde olmalidir.',
edit_confirm : 'Bu textarea i&ccedil;in WYSIWYG edit&ouml;r&uuml;n&uuml; kullanmak istermisiniz?',
insert_link_title : 'Link Ekle/Düzenle',
insert : 'Ekle',
update : 'G&uuml;ncelle',
cancel : '&#304;ptal',
insert_link_url : 'URL Ekle',
insert_link_target : 'Target Ekle',
insert_link_target_same : 'Ba&#287;lant&#305;y&#305; Ayn&#305; Pencerede A&ccedil;',
insert_link_target_blank : 'Ba&#287;lant&#305;y&#305; Yeni Pencerede A&ccedil;',
insert_image_title : 'Resim Ekle/Düzenle',
insert_image_src : 'Resim URL',
insert_image_alt : 'Resim Tan&#305;m&#305;',
help_desc : 'Yard&#305;m',
bold_img : "bold.gif",
italic_img : "italic.gif",
underline_img : "underline.gif",
clipboard_msg : 'Kopyala/Kes/Yap&#305;&#351;t&#305;r &ouml;zellikleri Mozilla ve Firefox da mevcut de&#287;il.\nBununla ilgili olarak daha fazla bilgi almak ister misiniz?',
popup_blocked : 'Taray&#305;c&#305;n&#305;z&#305;n popup-blocker &ouml;zelli&#287;i bu &ouml;zelli&#287;in &ccedil;al&#305;&#351;mas&#305;n&#305; engelliyor.\nBunun i&ccedil;in taray&#305;c&#305;n&#305;z&#305;n popup-blocker &ouml;zelli&#287;ini kapatman&#305;z gerekiyor.'
});
